package com.webflux.api.modules.project.service;

import com.webflux.api.modules.project.entity.Project;
import com.webflux.api.modules.project.repo.ICrud;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service("serviceCrud")
public class ServiceCrud implements IServiceCrud {

  @Autowired
  ICrud crud;


  /*╔══════════════════════════════╗
    ║   REACTIVE-MONGO-REPOSITORY  ║
    ╚══════════════════════════════╝*/
  @Override
  public Mono<Project> save(Project project) {

    return crud.save(project);
  }

  @Override
  public Mono<Project> update(Project project) {

    return crud.save(project);
  }

  @Override
  public Flux<Project> findAll() {

    return crud.findAll();
  }


  @Override
  public Mono<Project> findById(String projectId) {

    return crud.findById(projectId);
  }


  @Override
  public Mono<Void> deleteById(String projectId) {

    return crud.deleteById(projectId);
  }

  /*╔══════════════════════════════╗
  ║    AUTOGENERATED-QUERIES     ║
  ╚══════════════════════════════╝*/
  @Override
  public Flux<Project> findByName(String projectName) {

    return crud.findByName(projectName);
  }

}