# To test using DOCKER-COMPOSE TESTING - COMMENT testcontainer Annotations:
# - testcontainer\container\TcContainerReplicaset: All annotations
# - testcontainer\compose\TcCompose: All annotations
spring:
  profiles:
    active: replica-set
    group:
      replica-set: replicaset, log
      replica-set-auth: replicaset-auth, log
      stand-alone: standalone, log
server:
  port: ${PORT_API}