spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

udemy:
  mongodb:
    replicaset:
      name: ${RS_NAME}
      username: ${RS_USERNAME}
      password: ${RS_PASSWORD}
      database: ${RS_DB}
      primary: ${RS_PRIMARY}
      port: ${RS_PORT}
      authentication-database: ${RS_AUTH}