server:
  port: ${PORT_API}

spring:
  profiles:
    #    active will start the group, so the activation + group should have the same name
    active: group-dev
    group:
      group-dev: dev, log
      group-prod: prod, log