spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  data:
    mongodb:
      uri: ${REPLICASET_URI}
      database: ${REPLICASET_DB_NAME}
      replicaset_name: ${REPLICASET_NAME}
      authentication-database: ${REPLICASET_AUTH}