server:
  port: ${PORT_API}

spring:
  profiles:
    active: rs3-noauth
    group:
      rs1-noauth: singlenode-replicaset-noauth, log
      std-alone: standalone, log
      rs3-noauth: threenodes-replicaset-noauth, log