spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  data:
    mongodb:
      uri: ${URI}
      authentication-database: ${RS_AUTH}
      username: ${RS_USERNAME}
      password: ${RS_PASSWORD}