spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  data:
    mongodb:
      uri: ${REPLICASET_URI}
      database: ${MONGO_DATABASE}
      replicaset_name: ${REPLICASET_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: ${REPLICASET_AUTH}