server:
  port: ${PORT_API}

spring:
  autoconfigure:
    exclude: |
      org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,
      org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  data:
    mongodb:
      database: ${DB_MONGO_INITDB_DATABASE}
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_MONGO_INITDB_ROOT_USERNAME}
      password: ${DB_MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: ${DB_AUTH_MAN}