server:
  port: ${PORT_API}

spring:
  profiles:
    #    active will start the group, so the activation + group should have the same name
    active: gprod
    group:
      gdev: dev, log
      gprod: prod, log