spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

udemy:
  mongodb:
    replicaset:
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: ${MONGO_INITDB_DATABASE}
      name: ${MONGO_RS_NAME}
      primary: ${MONGO_RS_PRIMARY}
      port: ${MONGO_RS_PORT}
      authentication-database: ${MONGO_AUTH_MAN}
#  MONGO_RS_NAME: docker-rs
#  MONGO_RS_USERNAME: admin
#  MONGO_RS_PASSWORD: admin
#  MONGO_RS_PRIMARY: mongo1
#  MONGO_RS_PORT: 9042
#  MONGO_RS_DB: udemy
#  MONGO_RS_AUTH: admin
#  PORT_API: 8080
#udemy:
#  mongodb:
#    replicaset:
#      name: docker-rs
#      username: admin
#      password: admin
#      primary: mongo1
#      port: 9042
#      database: udemy
#      authentication-database: admin