server:
  port: ${PORT_API}

spring:
  profiles:
#    active: rs1-noauth
    active: rs3-noauth
#    active: std-alone
    group:
      rs1-noauth: replicaset-noauth, log
      rs3-noauth: replicaset-noauth, log
      std-alone: standalone, log