spring:
  profiles:
    active: replica-set-auth
    group:
      replica-set: replicaset, log
      replica-set-auth: replicaset-auth, log
      stand-alone: standalone, log
server:
  port: ${PORT_API}