server:
  port: ${PORT_API}

spring:
  profiles:
    active: production
    group:
      development-replicaset: development-rs1, log
      development-standalone: development-std, log
      production: production-rs3, log