version: "3.4"

x-common-variables:
  &env-vars
  MONGO_INITDB_DATABASE: api-db
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root
  DB_HOST: api-db
  DB_PORT: 27017
  DB_AUTH_MAN: admin
  PORT_API: 8080

volumes:
  api_vol:

networks:
  mongo-cluster:

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9042
    ports:
      - "9042:9042"
    networks:
      - mongo-cluster
    volumes:
      - ~/mongors/data1:/data/db
      - ./:/scripts/
      - api_vol:/data/db

  mongo2:
    container_name: mongo2
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet docker-rs --port 9142
    ports:
      - "9142:9142"
    networks:
      - mongo-cluster
    volumes:
      - ~/mongors/data2:/data/db

  mongo3:
    container_name: mongo3
    image: mongo:4.4.4
    restart: always
    ports:
      - "9242:9242"
    command: mongod --replSet docker-rs --port 9242
    networks:
      - mongo-cluster
    volumes:
      - ~/mongors/data3:/data/db

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api_vol:/data/db
    depends_on:
      - mongo1
    networks:
      - mongo-cluster
    environment:
      PROFILE: dev
      <<: *env-vars
      PORT_API: 8080
      PORT_DEBUG: 5005
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m