version: "3.4"

x-common-variables:
  &env-vars
  REPLICASET_URI: mongodb://mongo-prod1:27017/rs-db-1?replicaSet=singleRs
  REPLICASET_AUTH: admin
  REPLICASET_DB_NAME: rs-db-1
  PORT_API: 8080

volumes:
  api-vol:

networks:
  api-net:

services:
  mongo1:
    container_name: mongo-prod1
    image: mongo:4.4.4
    command: --replSet singleRs
    ports:
      - "27017:27017"
    networks:
      - api-net

  rs-setup:
    container_name: rs-setup
    image: mongo:4.4.4
    command: bash -c "
      sleep 5 &&
      mongo --host mongo-prod1 --port 27017 --eval \"rs.initiate()\" &&
      sleep 2 &&
      mongo --host mongo-prod1 --port 27017 --eval \"rs.status()\" &&
      sleep infinity"
    depends_on:
      - mongo1
    networks:
      - api-net

  api-rs:
    container_name: api-rs
    image: pauloportfolio/api-rs
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api-vol:/data/db
    depends_on:
      - rs-setup
    networks:
      - api-net
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m