version: "3.4"

x-common-variables:
  &env-vars
  URI: mongodb://mongo-prod1:27017/rs-db-1?replicaSet=singleRs
  RS_AUTH: admin
  RS_USERNAME: dev-rs
  RS_PASSWORD: dev-rs
  PORT_API: 8080

volumes:
  api-vol:

networks:
  api-net:

services:
  mongo1:
    container_name: mongo-prod1
    image: mongo:4.4.4
    command: --replSet singleRs
    ports:
      - "27017:27017"
    networks:
      - api-net

  replicaset-setup:
    container_name: replicaset-setup
    image: mongo:latest
    command: bash -c "
      sleep 5 &&
      mongo --host mongo-prod1 --port 27017 --eval \"rs.initiate()\" &&
      sleep 2 &&
      mongo --host mongo-prod1 --port 27017 --eval \"rs.status()\" &&
      sleep infinity"
    depends_on:
      - mongo1
    networks:
      - api-net

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api-vol:/data/db
    depends_on:
      - replicaset-setup
    networks:
      - api-net
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m