version: "3.4"

x-common-variables:
  &env-vars
  RS_ROOT_URI: mongodb://mongo-prod1:9042,mongo-prod2:9142,mongo-prod3:9242
  RS_DB: rs-db
  RS_NAME: devThreeNodesRs
  RS_AUTH: admin
  RS_USERNAME: dev-rs
  RS_PASSWORD: dev-rs
  PORT_API: 8080

volumes:
  api-vol:

networks:
  api-net:

services:
  mongo1:
    container_name: mongo-prod1
    image: mongo:4.4.4
    command: --replSet devThreeNodesRs --port 9042
    ports:
      - "9042:9042"
    networks:
      - api-net
    volumes:
      - ~/mongors/data1:/data/db
    depends_on:
      - mongo2

  mongo2:
    container_name: mongo-prod2
    image: mongo:4.4.4
    restart: always
    command: mongod --replSet devThreeNodesRs --port 9142
    ports:
      - "9142:9142"
    networks:
      - api-net
    volumes:
      - ~/mongors/data2:/data/db
    depends_on:
      - mongo3

  mongo3:
    container_name: mongo-prod3
    image: mongo:4.4.4
    restart: always
    ports:
      - "9242:9242"
    command: mongod --replSet devThreeNodesRs --port 9242
    networks:
      - api-net
    volumes:
      - ~/mongors/data3:/data/db

  api:
    container_name: api
    image: pauloportfolio/api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - api-vol
    depends_on:
      - mongo1
    networks:
      - api-net
    environment:
      PORT_DEBUG: 5005
      <<: *env-vars
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m